apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.42.1.5
    conditions:
      ready: false
      serving: false
      terminating: false
    nodeName: k3d-quickticket-lab78-server-0
    targetRef:
      kind: Pod
      name: events-7cbfc9d5fb-gd98q
      namespace: default
      uid: a49ae755-a404-481b-9da2-97ef5b4b033c
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-10-05T08:30:39Z"
    creationTimestamp: "2026-10-05T08:00:10Z"
    generateName: events-
    generation: 6
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: events
    name: events-8h5q9
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: events
      uid: e931110a-4dd2-4a02-ad6d-8a5a2fb69bf1
    resourceVersion: "4025"
    uid: de775833-2bb9-4e42-a293-af76452aaae9
  ports:
  - name: tcp
    port: 8081
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
