apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - port: {{ .Values.payments.port }}
      targetPort: {{ .Values.payments.port }}
