apiVersion: 1

contactPoints:
  - orgId: 1
    name: quickticket-alerts
    receivers:
      - uid: bfqc5vew4w3y9d
        type: webhook
        settings:
          httpMethod: POST
          url: http://webhook-receiver:19090/alerts
        disableResolveMessage: false
