apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  annotations:
    rollout.argoproj.io/revision: "7"
  creationTimestamp: "2026-10-05T00:46:02Z"
  generation: 4
  labels:
    app: gateway
    rollout-type: Step
    rollouts-pod-template-hash: 5bcbd9ff4
    step-index: "2"
  name: gateway-5bcbd9ff4-7-2
  namespace: default
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rollout
    name: gateway
    uid: 037a0ba0-a17c-470f-872e-0f44a04defd3
  resourceVersion: "49145"
  uid: 034722ee-e221-4ebb-90e7-9957c2d30220
spec:
  args:
  - name: canary-hash
    value: 5bcbd9ff4
  metrics:
  - count: 3
    failureLimit: 1
    initialDelay: 60s
    interval: 20s
    name: error-rate
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        authentication:
          oauth2: {}
          sigv4: {}
        query: |
          (
            sum(rate(gateway_requests_total{rs_hash="{{args.canary-hash}}",status=~"5.."}[60s]))
            or on() vector(0)
          )
          /
          sum(rate(gateway_requests_total{rs_hash="{{args.canary-hash}}"}[60s]))
    successCondition: result[0] < 0.05
status:
  completedAt: "2026-10-05T00:47:22Z"
  dryRunSummary: {}
  message: Metric "error-rate" assessed Failed due to failed (2) > failureLimit (1)
  metricResults:
  - count: 2
    failed: 2
    measurements:
    - finishedAt: "2026-10-05T00:47:02Z"
      phase: Failed
      startedAt: "2026-10-05T00:47:02Z"
      value: '[1]'
    - finishedAt: "2026-10-05T00:47:22Z"
      phase: Failed
      startedAt: "2026-10-05T00:47:22Z"
      value: '[1]'
    metadata:
      ResolvedPrometheusQuery: |
        (
          sum(rate(gateway_requests_total{rs_hash="5bcbd9ff4",status=~"5.."}[60s]))
          or on() vector(0)
        )
        /
        sum(rate(gateway_requests_total{rs_hash="5bcbd9ff4"}[60s]))
    name: error-rate
    phase: Failed
  phase: Failed
  runSummary:
    count: 1
    failed: 1
  startedAt: "2026-10-05T00:46:02Z"
